In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
os.chdir(r"C:\Users\HP\Documents")

In [3]:
data=pd.read_excel("Strokes_data.xls")

In [4]:
data

id  gender   age  hypertension  heart_disease ever_married  \
0      30669    Male   3.0             0              0           No   
1      30468    Male  58.0             1              0          Yes   
2      16523  Female   8.0             0              0           No   
3      56543  Female  70.0             0              0          Yes   
4      46136    Male  14.0             0              0           No   
...      ...     ...   ...           ...            ...          ...   
43395  56196  Female  10.0             0              0           No   
43396   5450  Female  56.0             0              0          Yes   
43397  28375  Female  82.0             1              0          Yes   
43398  27973    Male  40.0             0              0          Yes   
43399  36271  Female  82.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0          children          Rural              95.12  18.0              NaN   
1           Private          Urban              87.96  39.2     never smoked   
2           Private          Urban             110.89  17.6              NaN   
3           Private          Rural              69.04  35.9  formerly smoked   
4      Never_worked          Rural             161.28  19.1              NaN   
...             ...            ...                ...   ...              ...   
43395      children          Urban              58.64  20.4     never smoked   
43396      Govt_job          Urban             213.61  55.4  formerly smoked   
43397       Private          Urban              91.94  28.9  formerly smoked   
43398       Private          Urban              99.16  33.2     never smoked   
43399       Private          Urban              79.48  20.6     never smoked   

       stroke  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
43395       0  
43396       0  
43397       0  
43398       0  
43399       0  

[43400 rows x 12 columns]

In [5]:
data['smoking_status'].mode()

0    never smoked
dtype: object

In [6]:
data['smoking_status'] = data['smoking_status'].replace(np.nan,'never smoked')

In [7]:
data

id  gender   age  hypertension  heart_disease ever_married  \
0      30669    Male   3.0             0              0           No   
1      30468    Male  58.0             1              0          Yes   
2      16523  Female   8.0             0              0           No   
3      56543  Female  70.0             0              0          Yes   
4      46136    Male  14.0             0              0           No   
...      ...     ...   ...           ...            ...          ...   
43395  56196  Female  10.0             0              0           No   
43396   5450  Female  56.0             0              0          Yes   
43397  28375  Female  82.0             1              0          Yes   
43398  27973    Male  40.0             0              0          Yes   
43399  36271  Female  82.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0          children          Rural              95.12  18.0     never smoked   
1           Private          Urban              87.96  39.2     never smoked   
2           Private          Urban             110.89  17.6     never smoked   
3           Private          Rural              69.04  35.9  formerly smoked   
4      Never_worked          Rural             161.28  19.1     never smoked   
...             ...            ...                ...   ...              ...   
43395      children          Urban              58.64  20.4     never smoked   
43396      Govt_job          Urban             213.61  55.4  formerly smoked   
43397       Private          Urban              91.94  28.9  formerly smoked   
43398       Private          Urban              99.16  33.2     never smoked   
43399       Private          Urban              79.48  20.6     never smoked   

       stroke  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
43395       0  
43396       0  
43397       0  
43398       0  
43399       0  

[43400 rows x 12 columns]

In [8]:
Tdata=data[['gender','smoking_status']]

In [9]:
Tdata

gender   smoking_status
0        Male     never smoked
1        Male     never smoked
2      Female     never smoked
3      Female  formerly smoked
4        Male     never smoked
...       ...              ...
43395  Female     never smoked
43396  Female  formerly smoked
43397  Female  formerly smoked
43398    Male     never smoked
43399  Female     never smoked

[43400 rows x 2 columns]

In [10]:
Tdata.shape

(43400, 2)

In [11]:
Tdata.isnull().sum()

gender            0
smoking_status    0
dtype: int64

In [12]:
Table=pd.crosstab(Tdata.smoking_status,Tdata.gender)

In [13]:
Table

gender           Female   Male  Other
smoking_status                       
formerly smoked    4117   3370      6
never smoked      17867  11474      4
smokes             3681   2880      1

In [14]:
from scipy import stats

In [136]:
chi2_stat,p_value, dof, ex = stats.chi2_contingency(Table)

In [137]:
 stats.chi2_contingency(Table)

(126.48257410411993,
 2.2002510561383255e-26,
 4,
 array([[4.43105634e+03, 3.06004452e+03, 1.89914747e+00],
        [1.73534430e+04, 1.19841194e+04, 7.43767281e+00],
        [3.88050069e+03, 2.67983613e+03, 1.66317972e+00]]))

In [138]:
p_value

2.2002510561383255e-26

In [139]:
if(p_value<0.05):
    print('reject null hypothesis')
else:
    print('accept null hypo')

reject null hypothesis


In [ ]:
'''Hypothesis

Null:-Smoking habbit is not depend on gender
Alternate:- Smoking habbit depend on gender
'''

In [140]:
Tdata1=data[['Residence_type','smoking_status']]

In [141]:
Tdata1.isnull().sum()

Residence_type    0
smoking_status    0
dtype: int64

In [148]:
Table1=pd.crosstab(Tdata1.Residence_type,Tdata.smoking_status)

In [149]:
Table1

smoking_status  formerly smoked  never smoked  smokes
Residence_type                                       
Rural                      3772         14667    3205
Urban                      3721         14678    3357

In [150]:
chi2_stat,p_value, dof, ex = stats.chi2_contingency(Table1)

In [151]:
stats.chi2_contingency(Table1)

(3.5831167280985596,
 0.1667001875669629,
 2,
 array([[ 3736.8316129 , 14634.63548387,  3272.53290323],
        [ 3756.1683871 , 14710.36451613,  3289.46709677]]))

In [153]:
p_value

0.1667001875669629

In [154]:
if(p_value<0.05):
    print('reject null hypothesis')
else:
    print('accept null hypo')

accept null hypo


In [ ]:
'''Hypothesis

Null:-Smoking habbit is not depend on Residence_type
Alternate:- Smoking habbit depend on Residence_type
'''

In [168]:
Tdata2=data[['gender','smoking_status','Residence_type']]

In [169]:
Tdata2.isnull().sum()

gender            0
smoking_status    0
Residence_type    0
dtype: int64

In [171]:
Table2=pd.crosstab(Tdata2.smoking_status,[Tdata2.gender,Tdata2.Residence_type])

In [172]:
Table2

gender          Female        Male       Other      
Residence_type   Rural Urban Rural Urban Rural Urban
smoking_status                                      
formerly smoked   2084  2033  1684  1686     4     2
never smoked      8939  8928  5726  5748     2     2
smokes            1793  1888  1412  1468     0     1

In [173]:
chi2_stat,p_value, dof, ex = stats.chi2_contingency(Table2)

In [174]:
stats.chi2_contingency(Table)

(126.48257410411993,
 2.2002510561383255e-26,
 4,
 array([[4.43105634e+03, 3.06004452e+03, 1.89914747e+00],
        [1.73534430e+04, 1.19841194e+04, 7.43767281e+00],
        [3.88050069e+03, 2.67983613e+03, 1.66317972e+00]]))

In [175]:
p_value

1.7843110381524097e-23

In [176]:
if(p_value<0.05):
    print('reject null hypothesis')
else:
    print('accept null hypo')

reject null hypothesis


In [ ]:
'''Hypothesis

Null:-Smoking habbit is not depend on Residence_type & gender
Alternate:- Smoking habbit depend on Residence_type & gender
'''

'''
if chi.sq.cal.val > chi.sq.critical.val
    reject null hypothesis

'''